version: "3.8"
services:
  db:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_ROOT_PASSWORD: 'password123'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    volumes:
      - ./db_data:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - '8082:80'
    environment:
      PMA_HOST: db

  back:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PROFILE: docker
    ports:
      - 8091:8080
    depends_on:
      db:
        condition: service_healthy


  keycloak:
    image: quay.io/keycloak/keycloak:legacy
    container_name: keycloak
    volumes:
      - ./keycloak_data:/opt/jboss/keycloak/standalone/data
    environment:
      DB_VENDOR: MYSQL
      DB_ADDR: db
      DB_DATABASE: keycloak
      DB_USER: root
      DB_PASSWORD: password123
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    command:
      - -Djboss.http.port=9091
    ports:
      - 9091:9091
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl" , "--fail","http://localhost:9091/auth/" ]
      timeout: 20s
      retries: 10